
version: "3"

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: prvent
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "192.168.100.194:5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

volumes:
  db-data:
